const chapterData11 = {

"Units and Measurements": [
"Need for Measurement",
"Physical Quantities",
"Systems of Units",
"SI Units",
"Fundamental Units",
"Derived Units",
"Significant Figures",
"Errors in Measurement",
"Uncertainty in Results",
"Dimensions",
"Dimensional Formulae",
"Dimensional Analysis",
"Applications of Dimensional Analysis"
],

"Motion in a Straight Line": [
"Frame of Reference",
"Motion in a Straight Line",
"Uniform Motion",
"Non-Uniform Motion",
"Average Speed",
"Average Velocity",
"Instantaneous Velocity",
"Acceleration",
"Velocity-Time Graphs",
"Position-Time Graphs",
"Equations of Motion",
"Graphical Treatment",
"Differentiation in Kinematics",
"Integration in Kinematics"
],

"Motion in a Plane": [
"Scalars and Vectors",
"Position Vector",
"Displacement Vector",
"Vector Notation",
"Equality of Vectors",
"Multiplication of Vector by Scalar",
"Vector Addition",
"Vector Subtraction",
"Unit Vectors",
"Resolution of Vectors",
"Rectangular Components",
"Scalar Product",
"Vector Product",
"Projectile Motion",
"Relative Velocity",
"Uniform Circular Motion"
],

"Laws of Motion": [
"Inertia",
"Newton's First Law",
"Momentum",
"Newton's Second Law",
"Impulse",
"Newton's Third Law",
"Conservation of Linear Momentum",
"Applications of Momentum Conservation",
"Equilibrium of Concurrent Forces",
"Static Friction",
"Kinetic Friction",
"Laws of Friction",
"Rolling Friction",
"Lubrication",
"Centripetal Force",
"Dynamics of Uniform Circular Motion"
],

"Work, Energy and Power": [
"Work Done by Constant Force",
"Work Done by Variable Force",
"Kinetic Energy",
"Work Energy Theorem",
"Power",
"Potential Energy",
"Spring Potential Energy",
"Conservative Forces",
"Non-Conservative Forces",
"Motion in Vertical Circle",
"Elastic Collisions",
"Inelastic Collisions",
"One-Dimensional Collisions",
"Two-Dimensional Collisions"
],

"System of Particles and Rotational Motion": [
"Centre of Mass",
"Two Particle System",
"Centre of Mass Motion",
"Momentum Conservation",
"Centre of Mass of Rigid Body",
"Uniform Rod Centre of Mass",
"Moment of Force",
"Torque",
"Angular Momentum",
"Conservation of Angular Momentum",
"Rigid Body Equilibrium",
"Rotational Motion",
"Rotational Equations of Motion",
"Linear vs Rotational Motion",
"Moment of Inertia",
"Radius of Gyration"
],

"Gravitation": [
"Kepler's Laws",
"Universal Law of Gravitation",
"Acceleration Due to Gravity",
"Variation of g with Altitude",
"Variation of g with Depth",
"Gravitational Potential Energy",
"Gravitational Potential",
"Escape Velocity",
"Orbital Velocity",
"Satellite Motion",
"Energy of Orbiting Satellite"
],

"Mechanical Properties of Solids": [
"Elasticity",
"Stress",
"Strain",
"Stress-Strain Curve",
"Hooke's Law",
"Young's Modulus",
"Bulk Modulus",
"Shear Modulus",
"Poisson Ratio",
"Elastic Energy",
"Applications of Elasticity"
],

"Mechanical Properties of Fluids": [
"Fluid Pressure",
"Pressure Due to Fluid Column",
"Pascal's Law",
"Hydraulic Lift",
"Hydraulic Brakes",
"Effect of Gravity on Pressure",
"Viscosity",
"Stokes Law",
"Terminal Velocity",
"Streamline Flow",
"Turbulent Flow",
"Critical Velocity",
"Bernoulli's Theorem",
"Torricelli's Law",
"Dynamic Lift",
"Surface Energy",
"Surface Tension",
"Angle of Contact",
"Capillarity",
"Excess Pressure"
],

"Thermal Properties of Matter": [
"Heat",
"Temperature",
"Thermal Expansion",
"Expansion of Solids",
"Expansion of Liquids",
"Expansion of Gases",
"Anomalous Expansion of Water",
"Specific Heat Capacity",
"Calorimetry",
"Latent Heat",
"Conduction",
"Convection",
"Radiation",
"Thermal Conductivity",
"Blackbody Radiation",
"Wein's Displacement Law",
"Stefan's Law"
],

"Thermodynamics": [
"Thermal Equilibrium",
"Zeroth Law",
"Heat",
"Work",
"Internal Energy",
"First Law of Thermodynamics",
"Second Law of Thermodynamics",
"State Variables",
"Equation of State",
"Isothermal Process",
"Adiabatic Process",
"Reversible Process",
"Irreversible Process",
"Cyclic Process"
],

"Kinetic Theory": [
"Equation of State of Ideal Gas",
"Work Done in Compressing Gas",
"Assumptions of Kinetic Theory",
"Pressure of Gas",
"Kinetic Interpretation of Temperature",
"RMS Speed",
"Degrees of Freedom",
"Law of Equipartition of Energy",
"Specific Heat Capacity of Gases",
"Mean Free Path",
"Avogadro Number"
],

"Oscillations": [
"Periodic Motion",
"Time Period",
"Frequency",
"Displacement Function",
"Periodic Functions",
"Simple Harmonic Motion",
"Uniform Circular Motion and SHM",
"Phase",
"Loaded Spring",
"Restoring Force",
"Force Constant",
"Energy in SHM",
"Kinetic Energy in SHM",
"Potential Energy in SHM",
"Simple Pendulum",
"Time Period of Pendulum"
],

"Waves": [
"Wave Motion",
"Transverse Waves",
"Longitudinal Waves",
"Wave Speed",
"Progressive Wave Equation",
"Principle of Superposition",
"Reflection of Waves",
"Standing Waves",
"Strings",
"Organ Pipes",
"Fundamental Mode",
"Harmonics",
"Beats"
]
};
